apiVersion: v2
name: music-app
description: A Helm chart for Music Albums Service with Redis backend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - music
  - redis
  - golang
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled